# Generated by Django 3.2.3 on 2021-08-17 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_category_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
