# Generated by Django 3.2.3 on 2021-08-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
