# Generated by Django 3.2.3 on 2021-08-24 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
