# Generated by Django 3.2.3 on 2021-08-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=7, null=True),
        ),
    ]
