# Generated by Django 3.2.3 on 2021-08-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_actual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
